/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package program.sederhana.billing.warnet;

/**
 *
 * @author Ardy Sendleep
 */
public class Frame_billing_warnet extends javax.swing.JFrame {

    /**
     * Creates new form Frame_billing_warnet
     */
    public Frame_billing_warnet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Kom1 = new javax.swing.JRadioButton();
        Kom2 = new javax.swing.JRadioButton();
        Kom3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtBiaya = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtWaktu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLainnya = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        txtBayar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Kom4 = new javax.swing.JRadioButton();
        Kom5 = new javax.swing.JRadioButton();
        Kom6 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Total Bayar");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("No Komputer");

        Kom1.setText("Kom 1");
        Kom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kom1ActionPerformed(evt);
            }
        });

        Kom2.setText("Kom 2");
        Kom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kom2ActionPerformed(evt);
            }
        });

        Kom3.setText("Kom 3");
        Kom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kom3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Biaya Per Jam");

        txtBiaya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Lama Penggunaan");

        txtWaktu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Pesanan Lain (Snack)");

        txtLainnya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnHitung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        txtBayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Program Sederhana Billing Warnet");

        Kom4.setText("Kom 4");
        Kom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kom4ActionPerformed(evt);
            }
        });

        Kom5.setText("Kom 5");
        Kom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kom5ActionPerformed(evt);
            }
        });

        Kom6.setText("Kom 6");
        Kom6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kom6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHitung)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBiaya)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Kom4)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Kom5)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Kom6))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Kom1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Kom2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Kom3)))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBayar)
                                        .addComponent(txtWaktu)
                                        .addComponent(txtLainnya)))))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Kom1)
                    .addComponent(Kom3)
                    .addComponent(Kom2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kom4)
                    .addComponent(Kom6)
                    .addComponent(Kom5))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHitung)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Kom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kom1ActionPerformed
//        // TODO add your handling code here:
        txtBiaya.setText("3000");
    }//GEN-LAST:event_Kom1ActionPerformed

    private void Kom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kom2ActionPerformed
        // TODO add your handling code here:
        txtBiaya.setText("3000");
    }//GEN-LAST:event_Kom2ActionPerformed

    private void Kom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kom3ActionPerformed
        // TODO add your handling code here:
        txtBiaya.setText("3000");
    }//GEN-LAST:event_Kom3ActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:

        int a = Integer.parseInt(txtBiaya.getText());
        int b = Integer.parseInt(txtWaktu.getText());
        int c = Integer.parseInt(txtLainnya.getText());
        int hasilnya = a * b + c;
        txtBayar.setText("" + hasilnya);



    }//GEN-LAST:event_btnHitungActionPerformed

    private void Kom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kom4ActionPerformed
        // TODO add your handling code here:
        txtBiaya.setText("3000");
    }//GEN-LAST:event_Kom4ActionPerformed

    private void Kom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kom5ActionPerformed
        // TODO add your handling code here:
        txtBiaya.setText("3000");
    }//GEN-LAST:event_Kom5ActionPerformed

    private void Kom6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kom6ActionPerformed
        // TODO add your handling code here:
        txtBiaya.setText("3000");
    }//GEN-LAST:event_Kom6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_billing_warnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_billing_warnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_billing_warnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_billing_warnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame_billing_warnet().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Kom1;
    private javax.swing.JRadioButton Kom2;
    private javax.swing.JRadioButton Kom3;
    private javax.swing.JRadioButton Kom4;
    private javax.swing.JRadioButton Kom5;
    private javax.swing.JRadioButton Kom6;
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtBiaya;
    private javax.swing.JTextField txtLainnya;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables
}
